# Generated by Django 4.1.2 on 2022-10-13 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_task'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='decription',
            new_name='description',
        ),
    ]
